/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RunTiming } from './run-timing';

/**
 * Aggregate billing totals across all runs.
 */
export interface AggregateBillingTotals {
    /**
     * Total number of completed runs.
     */
    'runs': number;
    /**
     * Total input tokens.
     */
    'input_tokens': number;
    /**
     * Total output tokens.
     */
    'output_tokens': number;
    /**
     * Total tokens aggregated across all billing categories.
     */
    'total_tokens': number;
    /**
     * Total reasoning tokens.
     */
    'reasoning_tokens': number;
    /**
     * Total cache read tokens.
     */
    'cache_read_tokens': number;
    /**
     * Total cache write tokens.
     */
    'cache_write_tokens': number;
    /**
     * Total billed USD amount in micros.
     */
    'total_usd_micros'?: number | null;
    /**
     * Aggregate timing rollup across every completed run. Active timing sums work across stage visits, so `active_time_ms` can exceed `wall_time_ms`.
     */
    'timing': RunTiming;
}
