/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * One file entry in a strict multipart artifact upload manifest.
 */
export interface ArtifactBatchUploadEntry {
    /**
     * Multipart field name for the file part.
     */
    'part': string;
    /**
     * Relative artifact path to store.
     */
    'path': string;
    /**
     * Optional lowercase hex SHA-256 checksum for the file contents.
     */
    'sha256'?: string;
    /**
     * Optional exact byte length expected for the file part.
     */
    'expected_bytes'?: number;
    /**
     * Optional client-supplied content type for the file part.
     */
    'content_type'?: string;
}

