/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Readiness and defaults for starting an Ask Fabro session on this run.
 */
export interface AskFabro {
    'available': boolean;
    'unavailable_reason': AskFabroUnavailableReasonEnum | null;
    'default_model': string | null;
}

export const AskFabroUnavailableReasonEnum = {
    FEATURE_DISABLED: 'feature_disabled',
    NO_SANDBOX: 'no_sandbox',
    SANDBOX_NOT_READY: 'sandbox_not_ready',
    LLM_UNCONFIGURED: 'llm_unconfigured'
} as const;

export type AskFabroUnavailableReasonEnum = typeof AskFabroUnavailableReasonEnum[keyof typeof AskFabroUnavailableReasonEnum];
