/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Browser session user profile.
 */
export interface AuthSessionUser {
    'login': string;
    'name': string;
    'email': string;
    'idpIssuer'?: string;
    'idpSubject'?: string;
    'avatarUrl': string;
    'userUrl': string;
}

