/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request body for denying a pending run approval request.
 */
export interface DenyRunRequest {
    /**
     * Optional human-readable reason for denying execution. Empty or whitespace-only values are stored as absent.
     */
    'reason'?: string;
}
