/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GithubIntegrationStrategy } from './github-integration-strategy';
// May contain unused imports in some cases
// @ts-ignore
import type { IntegrationWebhooksSettings } from './integration-webhooks-settings';

export interface GithubIntegrationSettings {
    'enabled': boolean;
    'strategy': GithubIntegrationStrategy;
    'app_id': string | null;
    'client_id': string | null;
    'slug': string | null;
    'webhooks': IntegrationWebhooksSettings | null;
}



