/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Redacted summary of the sandbox provider selected during browser install.
 */
export interface InstallSandboxSummary {
    'provider': InstallSandboxSummaryProviderEnum;
    'api_key_saved'?: boolean;
    'allow_local'?: boolean;
}

export const InstallSandboxSummaryProviderEnum = {
    DOCKER: 'docker',
    DAYTONA: 'daytona'
} as const;

export type InstallSandboxSummaryProviderEnum = typeof InstallSandboxSummaryProviderEnum[keyof typeof InstallSandboxSummaryProviderEnum];
