/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Single-model test mode.
 */

export const ModelTestMode = {
    BASIC: 'basic',
    DEEP: 'deep'
} as const;

export type ModelTestMode = typeof ModelTestMode[keyof typeof ModelTestMode];



