/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Reason a pre-execution run is pending instead of runnable.
 */

export const PendingReason = {
    APPROVAL_REQUIRED: 'approval_required'
} as const;

export type PendingReason = typeof PendingReason[keyof typeof PendingReason];
