/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RunTiming } from './run-timing';

/**
 * Aggregate billing totals across all stages of a run.
 */
export interface RunBillingTotals {
    /**
     * Run-level timing rollup. `wall_time_ms` is summed across stage visits; active timing sums work across visits.
     */
    'timing': RunTiming;
    /**
     * Total input tokens consumed.
     */
    'input_tokens': number;
    /**
     * Total output tokens generated.
     */
    'output_tokens': number;
    /**
     * Total tokens aggregated across all billing categories.
     */
    'total_tokens': number;
    /**
     * Total reasoning tokens.
     */
    'reasoning_tokens': number;
    /**
     * Total cache read tokens.
     */
    'cache_read_tokens': number;
    /**
     * Total cache write tokens.
     */
    'cache_write_tokens': number;
    /**
     * Total billed USD amount in micros.
     */
    'total_usd_micros'?: number | null;
}
