/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Source that made a run runnable.
 */

export const RunRunnableSource = {
    START_REQUESTED: 'start_requested',
    APPROVED: 'approved'
} as const;

export type RunRunnableSource = typeof RunRunnableSource[keyof typeof RunRunnableSource];
