/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Run control action requested by the API.
 */

export const RunControlAction = {
    CANCEL: 'cancel',
    PAUSE: 'pause',
    UNPAUSE: 'unpause'
} as const;

export type RunControlAction = typeof RunControlAction[keyof typeof RunControlAction];



