/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { StageState } from './stage-state';

/**
 * A single stage in a run\'s workflow graph.
 */
export interface RunStage {
    /**
     * StageId in \"node_id@visit\" form, e.g. verify@2.
     */
    'id': string;
    /**
     * Human-readable stage name.
     */
    'name': string;
    'status': StageState;
    /**
     * Time spent in this stage, in seconds.
     */
    'duration_secs'?: number;
    /**
     * Node id in the workflow graph; multiple stages with different visits share the same node_id.
     */
    'node_id': string;
    /**
     * 1-based visit count; bumped each time the workflow re-enters this node.
     */
    'visit': number;
    /**
     * Wall-clock time the latest attempt of this stage started, if known.
     */
    'started_at'?: string | null;
}



