/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PendingReason } from './pending-reason';

export interface RunStatusPending {
    'kind': RunStatusPendingKindEnum;
    'reason': PendingReason;
}

export const RunStatusPendingKindEnum = {
    PENDING: 'pending'
} as const;

export type RunStatusPendingKindEnum = typeof RunStatusPendingKindEnum[keyof typeof RunStatusPendingKindEnum];
