/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { StageTiming } from './stage-timing';

/**
 * Terminal summary for one stage in a run conclusion.
 */
export interface StageSummary {
    'stage_id': string;
    'stage_label': string;
    'timing': StageTiming;
    'billing_usd_micros'?: number | null;
    'retries': number;
}
