/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RunControlAction } from './run-control-action';

/**
 * Durable run summary derived from the backing store.
 */
export interface StoreRunSummary {
    'run_id': string;
    'workflow_name'?: string;
    'workflow_slug'?: string;
    'goal'?: string;
    'labels': { [key: string]: string; };
    'host_repo_path'?: string;
    'start_time'?: string;
    'status'?: string;
    'status_reason'?: string;
    'pending_control'?: RunControlAction;
    'duration_ms'?: number;
    'total_cost'?: number;
}



