/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TodoStatus } from './todo-status';

/**
 * One projected todo / task item.
 */
export interface TodoProjection {
    'id': string;
    'status': TodoStatus;
    'order': number;
    'subject': string;
    'description'?: string;
    'active_form'?: string | null;
    'owner'?: string | null;
    'blocks'?: Array<string>;
    'blocked_by'?: Array<string>;
    'metadata'?: { [key: string]: any; };
}
