/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Lifecycle for a todo / task. `deleted` is reachable for Anthropic tasks; once observed, the todo is removed from the projection.
 */

export const TodoStatus = {
    PENDING: 'pending',
    IN_PROGRESS: 'in_progress',
    COMPLETED: 'completed',
    DELETED: 'deleted'
} as const;

export type TodoStatus = typeof TodoStatus[keyof typeof TodoStatus];
