/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TodoListKind } from './todo-list-kind';
// May contain unused imports in some cases
// @ts-ignore
import type { TodoProjection } from './todo-projection';

/**
 * All currently-projected todos for one `list_id`.
 */
export interface TodoListProjection {
    'kind': TodoListKind;
    'list_id': string;
    'items'?: Array<TodoProjection>;
}
