/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WorkflowLastRunSummary } from './workflow-last-run-summary';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkflowScheduleSummary } from './workflow-schedule-summary';

/**
 * Workflow summary shown in workflow list pages.
 */
export interface WorkflowListItem {
    'name': string;
    'slug': string;
    'filename': string;
    'last_run'?: WorkflowLastRunSummary | null;
    'schedule'?: WorkflowScheduleSummary | null;
}

