/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SignoffStatus } from './signoff-status';

/**
 * Request body to create a new signoff.
 */
export interface CreateSignoffRequest {
    /**
     * Control slug or ID.
     */
    'control': string;
    /**
     * Repository name.
     */
    'repository': string;
    /**
     * Git commit SHA.
     */
    'commit_sha': string;
    'status': SignoffStatus;
    /**
     * Optional URL with more details.
     */
    'url'?: string;
    /**
     * Optional human-readable description.
     */
    'description'?: string;
    /**
     * Freeform string identifying the logical origin.
     */
    'source'?: string;
}



