/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Local sandbox settings.
 */
export interface LocalSandboxConfiguration {
    /**
     * Git worktree mode for local sandbox.
     */
    'worktree_mode'?: LocalSandboxConfigurationWorktreeModeEnum;
}

export const LocalSandboxConfigurationWorktreeModeEnum = {
    ALWAYS: 'always',
    CLEAN: 'clean',
    DIRTY: 'dirty',
    NEVER: 'never'
} as const;

export type LocalSandboxConfigurationWorktreeModeEnum = typeof LocalSandboxConfigurationWorktreeModeEnum[keyof typeof LocalSandboxConfigurationWorktreeModeEnum];


