/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DaytonaConfiguration } from './daytona-configuration';
// May contain unused imports in some cases
// @ts-ignore
import type { ExeConfiguration } from './exe-configuration';
// May contain unused imports in some cases
// @ts-ignore
import type { LocalSandboxConfiguration } from './local-sandbox-configuration';

/**
 * Sandbox execution environment settings.
 */
export interface SandboxConfiguration {
    /**
     * Sandbox provider name.
     */
    'provider'?: string;
    /**
     * Whether to preserve the sandbox after the run.
     */
    'preserve'?: boolean;
    'daytona'?: DaytonaConfiguration;
    'exe'?: ExeConfiguration;
    'local'?: LocalSandboxConfiguration;
    /**
     * Environment variables injected into the sandbox.
     */
    'env'?: { [key: string]: string; };
}

