/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ControlReference } from './control-reference';
// May contain unused imports in some cases
// @ts-ignore
import type { RepositoryReference } from './repository-reference';
// May contain unused imports in some cases
// @ts-ignore
import type { SignoffStatus } from './signoff-status';

/**
 * A stamp of approval for a (control, repository, commit SHA) tuple.
 */
export interface Signoff {
    /**
     * Unique identifier (ULID).
     */
    'id': string;
    'control': ControlReference;
    'repository': RepositoryReference;
    /**
     * Git commit SHA this signoff applies to.
     */
    'commit_sha': string;
    'status': SignoffStatus;
    /**
     * Optional URL with more details about the signoff.
     */
    'url'?: string;
    /**
     * Optional human-readable description.
     */
    'description'?: string;
    /**
     * Freeform string identifying the logical origin of the signoff.
     */
    'source'?: string;
    /**
     * When the signoff was created.
     */
    'created_at': string;
}



