/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Aggregate usage totals across all runs.
 */
export interface AggregateUsageTotals {
    /**
     * Total number of completed runs.
     */
    'runs': number;
    /**
     * Total input tokens.
     */
    'input_tokens': number;
    /**
     * Total output tokens.
     */
    'output_tokens': number;
    /**
     * Total cost in USD.
     */
    'cost': number;
    /**
     * Total runtime in seconds.
     */
    'runtime_secs': number;
}

