/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CategoryReference } from './category-reference';
// May contain unused imports in some cases
// @ts-ignore
import type { VerificationType } from './verification-type';

/**
 * Core metadata about a verification control.
 */
export interface ControlInfo {
    /**
     * Human-readable control name.
     */
    'name': string;
    /**
     * URL-safe slug.
     */
    'slug': string;
    /**
     * Short description of what the control verifies.
     */
    'description': string;
    'type'?: VerificationType;
    'category': CategoryReference;
}



