/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FileDiff } from './file-diff';
// May contain unused imports in some cases
// @ts-ignore
import type { PaginationMeta } from './pagination-meta';

/**
 * Paginated list of file diffs produced by a run.
 */
export interface PaginatedRunFileList {
    'data': Array<FileDiff>;
    'meta': PaginationMeta;
}

