/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RetroStats } from './retro-stats';
// May contain unused imports in some cases
// @ts-ignore
import type { RunReference } from './run-reference';
// May contain unused imports in some cases
// @ts-ignore
import type { SmoothnessRating } from './smoothness-rating';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkflowReference } from './workflow-reference';

/**
 * Summary of a run retrospective shown in list views.
 */
export interface RetroListItem {
    'run': RunReference;
    'workflow': WorkflowReference;
    /**
     * Timestamp when the retro was generated.
     */
    'timestamp': string;
    'smoothness'?: SmoothnessRating;
    'stats': RetroStats;
    /**
     * Number of friction points identified in the retro.
     */
    'friction_point_count': number;
}



