/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BoardColumn } from './board-column';
// May contain unused imports in some cases
// @ts-ignore
import type { RepositoryReference } from './repository-reference';
// May contain unused imports in some cases
// @ts-ignore
import type { RunPullRequest } from './run-pull-request';
// May contain unused imports in some cases
// @ts-ignore
import type { RunQuestion } from './run-question';
// May contain unused imports in some cases
// @ts-ignore
import type { RunSandbox } from './run-sandbox';
// May contain unused imports in some cases
// @ts-ignore
import type { RunTimings } from './run-timings';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkflowReference } from './workflow-reference';

/**
 * Summary of a run shown in the board view.
 */
export interface RunListItem {
    /**
     * Unique run identifier (ULID).
     */
    'id': string;
    'repository': RepositoryReference;
    /**
     * Human-readable title describing the run\'s goal.
     */
    'title': string;
    'workflow': WorkflowReference;
    'status': BoardColumn;
    'pull_request'?: RunPullRequest;
    'timings'?: RunTimings;
    'sandbox'?: RunSandbox;
    'question'?: RunQuestion;
    /**
     * Timestamp when the run was created.
     */
    'created_at': string;
}



