/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { VerificationResult } from './verification-result';
// May contain unused imports in some cases
// @ts-ignore
import type { VerificationType } from './verification-type';

/**
 * A verification control result within a run.
 */
export interface RunVerificationControl {
    /**
     * Human-readable control name.
     */
    'name': string;
    /**
     * URL-safe slug for linking to verification detail page.
     */
    'slug': string;
    /**
     * Short description of what the control verifies.
     */
    'description': string;
    'type': VerificationType;
    'status': VerificationResult;
}



