/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Compute resources allocated to a sandbox.
 */
export interface SandboxResources {
    /**
     * Number of CPU cores.
     */
    'cpu': number;
    /**
     * Memory in GB.
     */
    'memory': number;
}

