/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ModelReference } from './model-reference';
// May contain unused imports in some cases
// @ts-ignore
import type { SessionTurn } from './session-turn';

/**
 * Full session record including metadata and the complete conversation history.
 */
export interface SessionDetail {
    /**
     * Unique session identifier.
     */
    'id': string;
    /**
     * Short title summarizing the session topic.
     */
    'title': string;
    'model': ModelReference;
    /**
     * Timestamp when the session was created.
     */
    'created_at': string;
    /**
     * Timestamp when the session was last updated (e.g. new turn added).
     */
    'updated_at': string;
    /**
     * Ordered list of conversation turns.
     */
    'turns': Array<SessionTurn>;
}

