/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request body for submitting an answer to a pending question. At least one of `value`, `selected_option_key`, or `selected_option_keys` must be provided. 
 */
export interface SubmitAnswerRequest {
    /**
     * Freeform answer text.
     */
    'value'?: string;
    /**
     * Key of the selected option (for single-select multiple-choice questions).
     */
    'selected_option_key'?: string;
    /**
     * Keys of selected options (for multi-select questions).
     */
    'selected_option_keys'?: Array<string>;
}

