/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Token and cost usage totals.
 */
export interface TokenUsage {
    /**
     * Number of input tokens consumed.
     */
    'input_tokens': number;
    /**
     * Number of output tokens generated.
     */
    'output_tokens': number;
    /**
     * Cost in USD.
     */
    'cost': number;
}

