/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ModelReference } from './model-reference';
// May contain unused imports in some cases
// @ts-ignore
import type { TokenUsage } from './token-usage';
// May contain unused imports in some cases
// @ts-ignore
import type { UsageStageRef } from './usage-stage-ref';

/**
 * Token and cost usage for a single stage within a run.
 */
export interface UsageStage {
    'stage': UsageStageRef;
    'model': ModelReference;
    'usage': TokenUsage;
    /**
     * Wall-clock runtime in seconds.
     */
    'runtime_secs': number;
}

