/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ModelReference } from './model-reference';
// May contain unused imports in some cases
// @ts-ignore
import type { TokenUsage } from './token-usage';

/**
 * Usage statistics grouped by model.
 */
export interface UsageByModel {
    'model': ModelReference;
    /**
     * Number of stages that used this model.
     */
    'stages': number;
    'usage': TokenUsage;
}

