/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { VerificationMode } from './verification-mode';
// May contain unused imports in some cases
// @ts-ignore
import type { VerificationResult } from './verification-result';
// May contain unused imports in some cases
// @ts-ignore
import type { VerificationType } from './verification-type';

/**
 * A verification control within a category, with performance metrics.
 */
export interface VerificationControl {
    /**
     * Human-readable control name.
     */
    'name': string;
    /**
     * URL-safe slug for API lookups.
     */
    'slug': string;
    /**
     * Short description of what the control verifies.
     */
    'description': string;
    'type': VerificationType;
    'mode'?: VerificationMode;
    /**
     * F1 score of the control\'s AI evaluator.
     */
    'f1'?: number;
    /**
     * Pass@1 rate — probability of passing on the first evaluation.
     */
    'pass_at_1'?: number;
    /**
     * Recent evaluation results (newest first).
     */
    'evaluations'?: Array<VerificationResult>;
}



