/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WorkflowLastRun } from './workflow-last-run';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkflowSchedule } from './workflow-schedule';

/**
 * Summary of a workflow shown in list views.
 */
export interface WorkflowListItem {
    /**
     * Human-readable workflow name.
     */
    'name': string;
    /**
     * URL-safe slug used in API paths.
     */
    'slug': string;
    /**
     * DOT graph filename.
     */
    'filename': string;
    'last_run'?: WorkflowLastRun;
    'schedule'?: WorkflowSchedule;
}

