_version = 1

[run.pull_request]
enabled = true
draft = false

[run.environment]
id = "fabro-dev"

[environments.fabro-dev]
provider = "daytona"

[environments.fabro-dev.lifecycle]
auto_stop = "30m"

[environments.fabro-dev.labels]
repo = "fabro-sh/fabro"

[environments.fabro-dev.image]
dockerfile = { path = "Dockerfile" }

[environments.fabro-dev.resources]
cpu = 8
memory = "16GB"
disk = "20GB"

# [[run.hooks]]
# id = "cargo-fmt"
# name = "cargo-fmt"
# event = "post_tool_use"
# matcher = "write_file|edit_file|apply_patch"
# script = "cargo +nightly-2026-04-14 fmt"
# blocking = true
